### ISSUE TITLE
Officer pictures come up werid intermittently

### ISSUE THREAD

**Issue by Cliftonz** [ius-csg/csghomepage#12]
Officer pictures are squished on mobile devices.

**Comment by Cliftonz** [comment]
This issue persists between all platforms and is fixed by a refresh of the page.
More digging needs to be done to find the cause.

**Comment by jasekiw** [comment]
I've seen these kinds of bugs before (I think it is a browser bug). They are usually fixed by using a different approach.

**Comment by jasekiw** [comment]
This issue is fixed by https://github.com/ius-csg/csghomepage/pull/22
