### ISSUE TITLE
Update linter to ignore iu list url

### ISSUE THREAD

**Issue by Cliftonz** [ius-csg/csghomepage#53]
Error we are getting.
`Run bundle exec htmlproofer --url-ignore '/cslabs' ./_site --check-html
  bundle exec htmlproofer --url-ignore '/cslabs' ./_site --check-html
  shell: /usr/bin/bash -e {0}
  env:
    working-directory: ./
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    BUILD_NUMBER: 33
Running ["ImageCheck", "HtmlCheck", "LinkCheck", "ScriptCheck"] on ["./_site"] on *.html... 

Checking 27 external links...
- ./_site/index.html
Ran on 3 files!
  *  External link https://list.ius.edu/sympa/subscribe/csg-announce-l failed: 302 Number of redirects hit maximum amount`

**Comment by TheOtherUnknown** [comment]
UITS is doing some odd ongoing maintenance to the mailing list system. That may be related.
